

Test GET /appdb/version/v1:
  stage: test_functions
  image: node:16
  script:
    - cd "functions/AppDB/Version/GET/v1"
    - npm install
    - npm run build
  rules:
      - changes:
        - functions/AppDB/Version/GET/v1/**/*

Staging GET /appdb/version/v1:
  stage: deploy_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 65492d5d01cedf27535a
  environment: 
    name: staging/get_appdb_version_v1
    url: $API_HOSTNAME/appdb/version/v1
  needs:
    - Test GET /appdb/version/v1
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
      - functions/AppDB/Version/GET/v1/**/*

Production GET /appdb/version/v1:
  stage: deploy_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 65492d5d01cedf27535a
  environment: 
    name: production/get_appdb_version_v1
    url: $API_HOSTNAME/appdb/version/v1
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
      - functions/AppDB/Version/GET/v1/**/*
      when: manual
        