
ports:
  - port: 3001
    onOpen: ignore
    visibility: public


tasks:
  - name: Install Parser and Appwrite
    init: cd parser/src && composer install && docker build . -t parser
    command: npm i -g appwrite-cli && appwrite client --endpoint https://appconsole-staging.jrbit.de/v1 --projectId 63a43bd7d5cb200f754a


vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    - TeamHub.teamhub
    - felixfbecker.php-debug
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    - GitLab.gitlab-workflow
    - DEVSENSE.composer-php-vscode
    - caponetto.vscode-diff-viewer
    - 42Crunch.vscode-openapi
