
tasks:
  - name: PHP FPM
    init: docker pull php:8.2-fpm-buster
    command: docker run --rm -p 9000:9000 -v /workspace:/workspace php:8.2-fpm-buster

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    - TeamHub.teamhub
    - felixfbecker.php-debug
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    - GitLab.gitlab-workflow
    - DEVSENSE.composer-php-vscode
    - caponetto.vscode-diff-viewer
    - 42Crunch.vscode-openapi
