# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- publish
- test_functions
- deploy_functions

include: 
   - "/functions/Service/GET/LegacyV1/.gitlab-ci.yml"
   - "/functions/Service/GET/v1/.gitlab-ci.yml"
   - "/functions/Service/GET/v2/.gitlab-ci.yml"
   - "/functions/Case/GET/v1/.gitlab-ci.yml"
   - "/functions/Case/GET/v2/.gitlab-ci.yml"
   - "/functions/Spam/DELETE/v1/.gitlab-ci.yml"
   - "/functions/Spam/GET/v1/.gitlab-ci.yml"
   - "/functions/Spam/POST/v1/.gitlab-ci.yml"
   - "/functions/AppDB/Exporter/.gitlab-ci.yml"
   - "/functions/AppDB/Version/GET/v1/.gitlab-ci.yml"

build_parser:
  stage: deploy_functions
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint:
    - ''
  script:
  - /kaniko/executor --context "${CI_PROJECT_DIR}/parser" --dockerfile "${CI_PROJECT_DIR}/parser/Dockerfile"
    --destination "${CI_REGISTRY_IMAGE}/parser/v2:latest"
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    changes:
      - parser/**/*
 

build_spamai:
  stage: deploy_functions
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint:
    - ''
  script:
  - /kaniko/executor --context "${CI_PROJECT_DIR}/spam_ai" --dockerfile "${CI_PROJECT_DIR}/spam_ai/Dockerfile"
    --destination "${CI_REGISTRY_IMAGE}/spamai:latest"
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    changes:
      - spam_ai/**/*


pages:
  stage: deploy
  before_script:
    - npm install swagger-ui-dist@5.10.0
    - cd spec/generator
    - npm install
    - npm run merge
  script:
    - cd $CI_PROJECT_DIR
    - mkdir public
    - cp -rp node_modules/swagger-ui-dist/* public
    - cp -rp swagger.yaml public/swagger.yaml
    - sed -i "s#https://petstore\.swagger\.io/v2/swagger\.json#swagger.yaml#g" public/index.html
  artifacts:
    paths:
      - public
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH