
ports:
  - name: Parser Endpoint
    description: Translates HTTP to Functions
    port: 80
    onOpen: notify

tasks:
  - name: Install Parser
    init: cd parser/src && composer install


  - name: PHP FPM
    init: sudo mkdir /run/php
    command: sudo /usr/sbin/php-fpm8.1 -F -R


  - name: Nginx
    command: sudo nginx -c ${GITPOD_REPO_ROOT}/parser/nginx/default.conf

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    - TeamHub.teamhub
    - felixfbecker.php-debug
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    - GitLab.gitlab-workflow
    - DEVSENSE.composer-php-vscode
    - caponetto.vscode-diff-viewer
    - 42Crunch.vscode-openapi
