# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- publish
- test_functions
- build_functions


build_parser:
  stage: build_functions
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint:
    - ''
  script:
  - /kaniko/executor --context "${CI_PROJECT_DIR}/parser" --dockerfile "${CI_PROJECT_DIR}/parser/Dockerfile"
    --destination "${CI_REGISTRY_IMAGE}/parser/v2:latest"
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    changes:
      - parser/**/*
 

build_spamai:
  stage: build_functions
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint:
    - ''
  script:
  - /kaniko/executor --context "${CI_PROJECT_DIR}/spam_ai" --dockerfile "${CI_PROJECT_DIR}/spam_ai/Dockerfile"
    --destination "${CI_REGISTRY_IMAGE}/spamai:latest"
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    changes:
      - spam_ai/**/*
        

#Build_API_Metrics:
#  stage: build_functions
#  image: node:16
#  script:
#    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT --key $APPWRITE_API_KEY
#    - appwrite deploy function --functionId 63a586a196b24923e0bd
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#      changes:
#        - functions/API Metrics/**/*

### GET /case/v1/ ###


Test_GET_case_v1:
  stage: test_functions
  image: node:16
  script:
    - cd "functions/Case/GET/v1"
    - npm install
    - npm run build
  rules:
      - changes:
        - functions/Case/GET/v1/**/*

Build_GET_case_v1:
  stage: build_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 63a4fddf25de17a1d58b
  needs:
    - Test_GET_case_v1
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        


### END GET /case/v1/ ###
### GET /service/v1/ ###

        
Test_GET_service_v1:
  stage: test_functions
  image: node:16
  script:
    - cd "functions/Service/GET/v1"
    - npm install
    - npm run build
  rules:
      - changes:
        - functions/Service/GET/v1/**/*
        
Build_GET_service_v1:
  stage: build_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 63a6cdddef3bbd180247
  needs:
    - Test_GET_service_v1
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


        
### END GET /service/v1/ ###
### GET /service/v2/ ###

        
Test_GET_service_v2:
  stage: test_functions
  image: node:16
  script:
    - cd "functions/Service/GET/v2"
    - npm install
    - npm run build
  rules:
      - changes:
        - functions/Service/GET/v2/**/*

        
Build_GET_service_v2:
  stage: build_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 6492c9a9ccf500f2220c
  needs:
    - Test_GET_service_v2
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

        
### END GET /service/v2/ ###
### DELETE /spam/v1/ ###

Test_DELETE_spam_v1:
  stage: test_functions
  image: node:16
  script:
    - cd "functions/Spam/DELETE/v1"
    - npm install
    - npm run build
  rules:
      - changes:
        - functions/Spam/DELETE/v1/**/*
        
Build_DELETE_spam_v1:
  stage: build_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 63ada74449c5b6abe2d6
  needs:
    - Test_DELETE_spam_v1
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

### END DELETE /spam/v1/ ###


### GET /spam/v1/ ###
#Test_GET_spam_v1:
#  stage: test_functions
#  image: node:16
#  script:
#    - cd "functions/Spam/GET/v1"
#    - npm install
#    - npm run build
#  rules:
#      - changes:
#        - functions/Spam/GET/v1/**/*

#Build_GET_spam_v1:
#  stage: build_functions
#  image: node:16
#  script:
#    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT --key $APPWRITE_API_KEY
#    - appwrite deploy function --functionId 63bd31d263522d513abf
#  needs:
#    - Test_GET_spam_v1
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

        
### END GET /spam/v1/ ###
### POST /spam/v1/ ###

Test_POST_spam_v1:
  stage: test_functions
  image: node:16
  script:
    - cd "functions/Spam/POST/v1"
    - npm install
    - npm run build
  rules:
      - changes:
        - functions/Spam/POST/v1/**/*
        
Build_POST_spam_v1:
  stage: build_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 63bd3c891af577cfa915
  needs:
    - Test_POST_spam_v1
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

### END POST /spam/v1/ ###
### GET /case/v2/ ###

Test_GET_case_v2:
  stage: test_functions
  image: node:16
  script:
    - cd "functions/Case/GET/v2"
    - npm install
    - npm run build
  rules:
      - changes:
        - functions/Case/GET/v2/**/*

Build_GET_case_v2:
  stage: build_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 64931a2451cea6ad3c18
  needs:
    - Test_GET_case_v2
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

### GET /case/v2/ ###

### DATA DUMP ###

Test_DATA_DUMP:
  stage: test_functions
  image: node:16
  script:
    - cd "functions/DB Dump"
    - npm install
    - npm run build
  rules:
      - changes:
        - functions/DB Dump/**/*

Build_DATA_DUMP:
  stage: build_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 64ae02b048a82447e87d
  needs:
    - Test_DATA_DUMP
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

### DATA DUMP ###


### AppDB ###

Test_AppDB_Exporter:
  stage: test_functions
  image: node:16
  script:
    - cd "functions/AppDB/Exporter"
    - npm install
    - npm run build
  rules:
      - changes:
        - functions/AppDB/Exporter/**/*

Build_AppDB_Exporter:
  stage: build_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 654901b409d4955a45e2
  needs:
    - Test_AppDB_Exporter
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

### AppDB ###


### GET /appdb/version/v1/ ###

Test_GET_appdb_version_v1:
  stage: test_functions
  image: node:16
  script:
    - cd "functions/AppDB/Version/GET/v1"
    - npm install
    - npm run build
  rules:
      - changes:
        - functions/AppDB/Version/GET/v1/**/*

Build_GET_appdb_version_v1:
  stage: build_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 65492d5d01cedf27535a
  needs:
    - Test_GET_appdb_version_v1
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

### GET /appdb/version/v1/ ###