
ports:
  - name: Parser Endpoint
    description: Translates HTTP to Functions
    port: 80
    onOpen: notify

tasks:
  - name: Install Parser and Appwrite
    init: cd parser/src && composer install && npm i -g appwrite-cli && exit

  - name: PHP FPM
    command: sudo mkdir /run/php; sudo /usr/sbin/php-fpm8.1 -F -R


  - name: Nginx
    command: sudo nginx -c ${GITPOD_REPO_ROOT}/parser/nginx/local.conf



  - name: Install Function GET case/v1
    command: cd functions/Case/GET/v1 && npm install && exit

  - name: Install Function GET service/v1
    command: cd functions/Service/GET/v1 && npm install && exit

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    - TeamHub.teamhub
    - felixfbecker.php-debug
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    - GitLab.gitlab-workflow
    - DEVSENSE.composer-php-vscode
    - caponetto.vscode-diff-viewer
    - 42Crunch.vscode-openapi
