

Test AppDB Exporter:
  stage: test_functions
  image: node:16
  script:
    - cd "functions/AppDB/Exporter"
    - npm install
    - npm run build
  rules:
      - changes:
        - functions/AppDB/Exporter/**/*

Staging AppDB Exporter:
  stage: deploy_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME_STAGING --projectId $APPWRITE_PROJECT --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 654901b409d4955a45e2
  environment: staging/appdb_exporter
  needs:
    - Test AppDB Exporter
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
      - functions/AppDB/Exporter/**/*

Production AppDB Exporter:
  stage: deploy_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME_PROD --projectId $APPWRITE_PROJECT --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 654901b409d4955a45e2
  environment: production/appdb_exporter
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
      - functions/AppDB/Exporter/**/*
      when: manual
        