

Test GET /spam/v1:
  stage: test_functions
  image: node:16
  script:
    - cd "functions/Spam/GET/v1"
    - npm install
    - npm run build
  rules:
      - changes:
        - functions/Spam/GET/v1/**/*

Staging GET /spam/v1:
  stage: deploy_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME_STAGING --projectId $APPWRITE_PROJECT --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 63bd31d263522d513abf
  environment: staging/get_spam_v1
  needs:
    - Test GET /spam/v1
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
      - functions/Spam/GET/v1/**/*

Production GET /spam/v1:
  stage: deploy_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME_PROD --projectId $APPWRITE_PROJECT --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 63bd31d263522d513abf
  environment: production/get_spam_v1
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
        