/service/v2/:
  get:
    tags:
      - Service
    summary: Get all services in a paginated list
    description: Gets the whole service database in a pagination
    parameters:
      - name: page
        in: query
        description: Index of the Page you want to query, only applicable if "service" is not set.
        required: false
        schema:
          type: integer
          default: "1"
      - name: id
        in: query
        description: ID of a service to return
        required: false
        schema:
          type: integer
    responses:
      "200":
        description: Success
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/all-services-v2"
                - $ref: "#/components/schemas/single-service-v2"
      "400":
        $ref: "./errors/400.yaml"
      "404":
        $ref: "./errors/404.yaml"
      "429":
        $ref: "../../../../../../spec/errors/429.yaml"
