

Test GET /case/v1:
  stage: test_functions
  image: node:16
  script:
    - cd "functions/public/Case/GET/v1"
    - npm install
    - npm run build
  rules:
      - changes:
        - functions/public/Case/GET/v1/**/*

Staging GET /case/v1:
  stage: deploy_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 63a4fddf25de17a1d58b
  environment: 
    name: staging/get_case_v1
    url: $API_HOSTNAME/case/v1
  needs:
    - Test GET /case/v1
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
      - functions/public/Case/GET/v1/**/*

Production GET /case/v1:
  stage: deploy_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 63a4fddf25de17a1d58b
  environment: 
    name: production/get_case_v1
    url: $API_HOSTNAME/case/v1
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
      - functions/public/Case/GET/v1/**/*
      when: manual
        