

Test DELETE /spam/v1:
  stage: test_functions
  image: node:16
  script:
    - cd "functions/internal/Spam/DELETE/v1"
    - npm install
    - npm run build
  rules:
      - changes:
        - functions/internal/Spam/DELETE/v1/**/*

Staging DELETE /spam/v1:
  stage: deploy_functions
  image: node:16
  script:
    - npm i -g appwrite-cli &^& appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 63ada74449c5b6abe2d6
  environment: 
    name: staging/delete_spam_v1
    url: $API_HOSTNAME/spam/v1
  needs:
    - Test DELETE /spam/v1
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
      - functions/internal/Spam/DELETE/v1/**/*

Production DELETE /spam/v1:
  stage: deploy_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 63ada74449c5b6abe2d6
  environment: 
    name: production/delete_spam_v1
    url: $API_HOSTNAME/spam/v1
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
      - functions/internal/Spam/DELETE/v1/**/*
      when: manual
        